os: osx
osx_image: xcode9.1

before_install:
  - brew update
  - brew outdated
  - brew tap rockyluke/iot

install:
  - ruby --version
  - brew install hue

script:
  - hue help

notifications:
  email:
    on_success: never
    on_failure: always
